// :sdk — the hand-written Shomer.AI client library.
// Pure Kotlin/JVM (no android.*), per docs/design/sdk/design.md §2.5.

plugins {
    kotlin("jvm")
    `java-library`
}

// Target Java-17 bytecode using whatever JDK (17+) runs Gradle — avoids requiring
// a separate JDK-17 toolchain install (the Android Studio JBR is JDK 21).
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}

dependencies {
    // Coroutines are part of the public API (suspend functions on ShomerApi).
    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")

    // Wire layer — implementation details, not exposed to consumers.
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("com.squareup.moshi:moshi:1.15.1")
    implementation("com.squareup.moshi:moshi-kotlin:1.15.1") // reflective KotlinJsonAdapterFactory

    // SLF4J API only; the runtime binding is provided by the caller (Android Timber bridge,
    // or slf4j-simple in tests). This keeps the SDK dependency-light.
    api("org.slf4j:slf4j-api:2.0.9")

    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.12.0")
    testImplementation("junit:junit:4.13.2")
    testRuntimeOnly("org.slf4j:slf4j-simple:2.0.9")
}

tasks.test {
    useJUnit()
    testLogging { events("passed", "skipped", "failed") }
}

// ---------------------------------------------------------------------------
// Generate SdkBuildConfig.kt so SdkConfig.sdkVersion has a real value without
// depending on Android's BuildConfig (LLD §2.4 / §6.2 reference BuildConfig.SDK_VERSION;
// on a plain JVM library we synthesize the equivalent constant here).
// ---------------------------------------------------------------------------
val generatedSrcDir = layout.buildDirectory.dir("generated/sdkbuildconfig/kotlin")

val generateSdkBuildConfig by tasks.registering {
    val outDir = generatedSrcDir
    val ver = project.version.toString()
    inputs.property("version", ver)
    outputs.dir(outDir)
    doLast {
        val pkgDir = outDir.get().asFile.resolve("com/shomer/sdk")
        pkgDir.mkdirs()
        pkgDir.resolve("SdkBuildConfig.kt").writeText(
            """
            package com.shomer.sdk

            /** Generated by Gradle from project.version — do not edit. */
            internal object SdkBuildConfig {
                const val SDK_VERSION: String = "$ver"
            }

            """.trimIndent() + "\n",
        )
    }
}

sourceSets.named("main") {
    kotlin.srcDir(generatedSrcDir)
}

tasks.named("compileKotlin") {
    dependsOn(generateSdkBuildConfig)
}
